const API='https://klaskacubfmbtuvcrisr.supabase.co/functions/v1/grocery-api';
const cats=['Produce','Meat','Dairy','Pantry','Frozen','Household','Other'];
let items=[],search='';
const listEl=document.getElementById('list'),toastEl=document.getElementById('toast'),statusEl=document.getElementById('status');
const setupEl=document.getElementById('setup'),mainEl=document.getElementById('main'),whoEl=document.getElementById('who');
let who=localStorage.getItem('floWho')||'',label=localStorage.getItem('floLabel')||'';
const hash=new URLSearchParams(location.hash.replace(/^#/,''));
if(hash.get('who')){who=hash.get('who')||'';label=hash.get('label')||'';localStorage.setItem('floWho',who);localStorage.setItem('floLabel',label);history.replaceState(null,'',location.pathname+location.search)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){toastEl.textContent=t;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1700)}
async function api(action,method='GET',body,id){const u=new URL(API);u.searchParams.set('who',who);u.searchParams.set('action',action);if(id)u.searchParams.set('id',id);const r=await fetch(u,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok){let x={};try{x=await r.json()}catch{};throw Error(x.error||('Request failed '+r.status))}return r.json()}
function visible(){return items.filter(x=>!search||x.name.toLowerCase().includes(search.toLowerCase()))}
function renderList(){const a=visible();let html='';for(const c of cats){const rows=a.filter(x=>x.category===c);if(!rows.length)continue;html+='<div class="group">'+c+'</div><div class="card listcard">'+rows.map(x=>'<div class="item '+(x.completed?'done':'')+'"><input class="check" type="checkbox" '+(x.completed?'checked':'')+' data-check="'+x.id+'"><div><div class="name">'+esc(x.name)+'</div><div class="details">'+[x.added_by?('added by '+x.added_by):'',x.completed_by&&x.completed?('checked by '+x.completed_by):''].filter(Boolean).map(esc).join(' · ')+'</div></div><button class="more" data-more="'+x.id+'" aria-label="Edit item">•••</button></div>').join('')+'</div>'}if(!html)html='<div class="card empty">Nothing on the list right now.</div>';listEl.innerHTML=html;document.querySelectorAll('[data-check]').forEach(c=>c.onchange=()=>toggle(c.dataset.check,c.checked));document.querySelectorAll('[data-more]').forEach(b=>b.onclick=()=>editItem(b.dataset.more))}
async function refresh(silent=false){try{const r=await api('list');items=r.items||[];statusEl.textContent='Synced';statusEl.className='status';renderList()}catch(e){statusEl.textContent='Offline';if(!silent)toast(e.message)}}
async function addItem(){const input=document.getElementById('new');const n=input.value.trim();if(!n)return;try{await api('add','POST',{name:n});input.value='';await refresh()}catch(e){toast(e.message)}}
async function toggle(id,completed){try{await api('update','PATCH',{completed},id);await refresh(true)}catch(e){toast(e.message)}}
async function editItem(id){const x=items.find(i=>i.id===id);if(!x)return;const name=prompt('Item name',x.name);if(name===null)return;if(!name.trim()){if(confirm('Delete this item?')){try{await api('delete','DELETE',null,id);await refresh()}catch(e){toast(e.message)}}return}try{await api('update','PATCH',{name:name.trim()},id);await refresh()}catch(e){toast(e.message)}}
async function clearDone(){if(!items.some(x=>x.completed))return;if(!confirm('Clear completed items?'))return;try{await api('clear','POST',{});await refresh()}catch(e){toast(e.message)}}
if(!who){setupEl.hidden=false;statusEl.textContent='Setup needed'}else{mainEl.hidden=false;whoEl.textContent=(label||'Household')+' · shared household list';document.getElementById('add').onclick=addItem;document.getElementById('new').onkeydown=e=>{if(e.key==='Enter')addItem()};document.getElementById('clear').onclick=clearDone;document.getElementById('search').oninput=e=>{search=e.target.value;renderList()};refresh();setInterval(()=>{if(document.visibilityState==='visible')refresh(true)},4000)}